"""
Rhodawk AI — OSS-Fuzz Submission Pipeline (GAP 15)
===================================================
Automates the boilerplate work required to onboard a Rhodawk-discovered
fuzz harness into Google's OSS-Fuzz infrastructure.

For any candidate Python project the pipeline:
  1. **Generates a project layout** matching the OSS-Fuzz spec:
       projects/<name>/
         ├── project.yaml      (language, primary contact, sanitizers)
         ├── Dockerfile        (FROM gcr.io/oss-fuzz-base/base-builder-python)
         ├── build.sh          (compiles every harness with libFuzzer)
         └── <harness>.py      (Atheris-instrumented entry points)
  2. **Validates** the layout against OSS-Fuzz's published schema.
  3. **Optionally opens a pull request** against the
     ``google/oss-fuzz`` repository via the GitHub REST API. Requires
     ``OSS_FUZZ_GH_TOKEN`` with ``public_repo`` + ``pull_request`` scopes
     and ``OSS_FUZZ_FORK_OWNER`` (the user/org that already forked
     ``google/oss-fuzz``).
  4. **Records every submission** in ``oss_fuzz_submissions.sqlite`` so
     the orchestrator can avoid duplicate PRs and surface status in the
     dashboard.

Operator workflow
-----------------
>>> from oss_fuzz_pipeline import build_submission, submit_to_oss_fuzz
>>> sub = build_submission(
...     project_name='rhodawk-target',
...     repo_url='https://github.com/example/awesome-lib',
...     primary_contact='security@example.com',
...     harnesses=[{'name': 'fuzz_parser', 'source': PARSER_HARNESS_PY}],
... )
>>> result = submit_to_oss_fuzz(sub, dry_run=False)

Dry-run mode (default ``True``) skips the network calls and only
validates the layout — used by CI to lint generated harnesses before
the operator clicks "submit".

Environment variables
---------------------
``OSS_FUZZ_OUT_DIR``      Default ``/data/oss_fuzz_submissions``.
``OSS_FUZZ_DB``           Default ``/data/oss_fuzz_submissions.sqlite``.
``OSS_FUZZ_GH_TOKEN``     GitHub PAT with PR rights on the operator fork.
``OSS_FUZZ_FORK_OWNER``   GitHub user/org that owns the operator fork.
``OSS_FUZZ_BASE_BRANCH``  Default ``master`` (upstream main branch).
"""

from __future__ import annotations

import json
import logging
import os
import re
import shutil
import sqlite3
import time
from dataclasses import asdict, dataclass, field
from typing import Optional

LOG = logging.getLogger("rhodawk.oss_fuzz_pipeline")
if not LOG.handlers:
    logging.basicConfig(
        level=logging.INFO,
        format="[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s",
    )

OUT_DIR        = os.getenv("OSS_FUZZ_OUT_DIR", "/data/oss_fuzz_submissions")
SUBMISSION_DB  = os.getenv("OSS_FUZZ_DB",      "/data/oss_fuzz_submissions.sqlite")
GH_TOKEN       = os.getenv("OSS_FUZZ_GH_TOKEN", "")
FORK_OWNER     = os.getenv("OSS_FUZZ_FORK_OWNER", "")
BASE_BRANCH    = os.getenv("OSS_FUZZ_BASE_BRANCH", "master")
UPSTREAM_OWNER = "google"
UPSTREAM_REPO  = "oss-fuzz"

PROJECT_NAME_RE = re.compile(r"^[a-z0-9][a-z0-9\-_]{1,38}$")


# ──────────────────────────────────────────────────────────────────────
@dataclass
class FuzzHarness:
    name:   str             # e.g. fuzz_parser
    source: str             # full Python source — must call atheris.Setup
    notes:  str = ""

    def filename(self) -> str:
        return f"{self.name}.py"


@dataclass
class OSSFuzzSubmission:
    project_name:    str
    repo_url:        str
    primary_contact: str
    sanitizers:      list[str] = field(default_factory=lambda: ["address", "undefined"])
    fuzzing_engines: list[str] = field(default_factory=lambda: ["libfuzzer"])
    auto_ccs:        list[str] = field(default_factory=list)
    harnesses:       list[FuzzHarness] = field(default_factory=list)
    out_dir:         str = ""
    notes:           str = ""

    def to_dict(self) -> dict:
        d = asdict(self)
        d["harnesses"] = [asdict(h) for h in self.harnesses]
        return d


# ──────────────────────────────────────────────────────────────────────
# OSS-Fuzz template files
# ──────────────────────────────────────────────────────────────────────
def _project_yaml(sub: OSSFuzzSubmission) -> str:
    auto_ccs = "\n".join(f"  - {c}" for c in sub.auto_ccs) or "  []"
    return (
        f"homepage: \"{sub.repo_url}\"\n"
        f"language: python\n"
        f"primary_contact: \"{sub.primary_contact}\"\n"
        f"main_repo: \"{sub.repo_url}\"\n"
        f"sanitizers:\n" + "\n".join(f"  - {s}" for s in sub.sanitizers) + "\n"
        f"fuzzing_engines:\n" + "\n".join(f"  - {e}" for e in sub.fuzzing_engines) + "\n"
        f"auto_ccs:\n{auto_ccs}\n"
    )


def _dockerfile(sub: OSSFuzzSubmission) -> str:
    return (
        "# Auto-generated by rhodawk oss_fuzz_pipeline\n"
        "FROM gcr.io/oss-fuzz-base/base-builder-python\n"
        "RUN apt-get update && apt-get install -y --no-install-recommends \\\n"
        "    git build-essential && rm -rf /var/lib/apt/lists/*\n"
        f'RUN git clone --depth=1 {sub.repo_url} $SRC/{sub.project_name}\n'
        f'WORKDIR $SRC/{sub.project_name}\n'
        f'COPY build.sh $SRC/build.sh\n'
        + "".join(
            f'COPY {h.filename()} $SRC/{h.filename()}\n'
            for h in sub.harnesses
        )
    )


def _build_sh(sub: OSSFuzzSubmission) -> str:
    lines = [
        "#!/bin/bash -eu",
        "# Auto-generated by rhodawk oss_fuzz_pipeline.",
        f"cd $SRC/{sub.project_name}",
        "pip3 install --no-cache-dir .",
        "",
    ]
    for h in sub.harnesses:
        lines.append(f"compile_python_fuzzer $SRC/{h.filename()}")
    return "\n".join(lines) + "\n"


# ──────────────────────────────────────────────────────────────────────
# Validation
# ──────────────────────────────────────────────────────────────────────
class SubmissionError(Exception):
    """Raised when a generated submission fails validation."""


def _validate(sub: OSSFuzzSubmission) -> None:
    if not PROJECT_NAME_RE.match(sub.project_name):
        raise SubmissionError(
            f"project_name '{sub.project_name}' does not match {PROJECT_NAME_RE.pattern}"
        )
    if not sub.primary_contact or "@" not in sub.primary_contact:
        raise SubmissionError("primary_contact must be a valid email")
    if not sub.repo_url.startswith(("https://", "git@")):
        raise SubmissionError("repo_url must start with https:// or git@")
    if not sub.harnesses:
        raise SubmissionError("at least one harness is required")
    seen = set()
    for h in sub.harnesses:
        if not re.match(r"^[a-z0-9_]+$", h.name):
            raise SubmissionError(f"invalid harness name '{h.name}'")
        if h.name in seen:
            raise SubmissionError(f"duplicate harness name '{h.name}'")
        seen.add(h.name)
        if "atheris" not in h.source:
            raise SubmissionError(
                f"harness '{h.name}' must import and use atheris (libFuzzer)"
            )


# ──────────────────────────────────────────────────────────────────────
# Submission DB
# ──────────────────────────────────────────────────────────────────────
def _init_db() -> None:
    os.makedirs(os.path.dirname(SUBMISSION_DB), exist_ok=True)
    with sqlite3.connect(SUBMISSION_DB) as c:
        c.execute(
            """
            CREATE TABLE IF NOT EXISTS submissions (
                project_name    TEXT PRIMARY KEY,
                repo_url        TEXT,
                primary_contact TEXT,
                pr_url          TEXT,
                pr_number       INTEGER,
                status          TEXT,
                created_at      REAL,
                updated_at      REAL,
                manifest_json   TEXT
            )
            """
        )
        c.commit()


def _record(sub: OSSFuzzSubmission, *, status: str,
            pr_url: str = "", pr_number: int = 0) -> None:
    _init_db()
    now = time.time()
    with sqlite3.connect(SUBMISSION_DB) as c:
        c.execute(
            """
            INSERT INTO submissions
                (project_name, repo_url, primary_contact, pr_url, pr_number,
                 status, created_at, updated_at, manifest_json)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(project_name) DO UPDATE SET
                pr_url = excluded.pr_url,
                pr_number = excluded.pr_number,
                status = excluded.status,
                updated_at = excluded.updated_at,
                manifest_json = excluded.manifest_json
            """,
            (
                sub.project_name, sub.repo_url, sub.primary_contact,
                pr_url, pr_number, status, now, now,
                json.dumps(sub.to_dict()),
            ),
        )
        c.commit()


def list_submissions() -> list[dict]:
    _init_db()
    with sqlite3.connect(SUBMISSION_DB) as c:
        c.row_factory = sqlite3.Row
        rows = c.execute(
            "SELECT * FROM submissions ORDER BY updated_at DESC"
        ).fetchall()
    return [dict(r) for r in rows]


# ──────────────────────────────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────────────────────────────
def build_submission(
    project_name: str,
    repo_url: str,
    primary_contact: str,
    harnesses: list[dict],
    *,
    sanitizers: Optional[list[str]] = None,
    fuzzing_engines: Optional[list[str]] = None,
    auto_ccs: Optional[list[str]] = None,
    notes: str = "",
) -> OSSFuzzSubmission:
    """Materialise an OSS-Fuzz project layout on disk and validate it."""
    sub = OSSFuzzSubmission(
        project_name=project_name,
        repo_url=repo_url,
        primary_contact=primary_contact,
        sanitizers=sanitizers or ["address", "undefined"],
        fuzzing_engines=fuzzing_engines or ["libfuzzer"],
        auto_ccs=auto_ccs or [],
        harnesses=[FuzzHarness(**h) for h in harnesses],
        notes=notes,
    )
    _validate(sub)

    out_dir = os.path.join(OUT_DIR, project_name)
    if os.path.isdir(out_dir):
        shutil.rmtree(out_dir)
    os.makedirs(out_dir, exist_ok=True)

    with open(os.path.join(out_dir, "project.yaml"), "w") as fh:
        fh.write(_project_yaml(sub))
    with open(os.path.join(out_dir, "Dockerfile"), "w") as fh:
        fh.write(_dockerfile(sub))
    with open(os.path.join(out_dir, "build.sh"), "w") as fh:
        fh.write(_build_sh(sub))
    os.chmod(os.path.join(out_dir, "build.sh"), 0o755)
    for h in sub.harnesses:
        with open(os.path.join(out_dir, h.filename()), "w") as fh:
            fh.write(h.source)

    sub.out_dir = out_dir
    LOG.info("Built OSS-Fuzz layout at %s", out_dir)
    _record(sub, status="DRAFTED")
    return sub


# ──────────────────────────────────────────────────────────────────────
# GitHub PR submission
# ──────────────────────────────────────────────────────────────────────
def _gh(method: str, path: str, body: Optional[dict] = None) -> dict:
    import urllib.request as _u
    if not GH_TOKEN:
        raise SubmissionError("OSS_FUZZ_GH_TOKEN is not set")
    req = _u.Request(
        f"https://api.github.com{path}",
        method=method,
        data=(json.dumps(body).encode() if body is not None else None),
        headers={
            "Authorization": f"token {GH_TOKEN}",
            "Accept":       "application/vnd.github+json",
            "User-Agent":   "rhodawk-oss-fuzz-pipeline",
            "Content-Type": "application/json",
        },
    )
    try:
        with _u.urlopen(req, timeout=60) as resp:
            return json.loads(resp.read().decode())
    except Exception as exc:                                # noqa: BLE001
        raise SubmissionError(f"GitHub API {method} {path} failed: {exc}") from exc


def submit_to_oss_fuzz(sub: OSSFuzzSubmission, *, dry_run: bool = True) -> dict:
    """Open a PR against ``google/oss-fuzz`` adding the project.

    When ``dry_run=True`` (default) the function only validates the
    on-disk layout and returns a manifest. Set ``dry_run=False`` and
    provide ``OSS_FUZZ_GH_TOKEN`` + ``OSS_FUZZ_FORK_OWNER`` to actually
    push the branch to your fork and open the PR upstream.
    """
    _validate(sub)
    if not sub.out_dir or not os.path.isdir(sub.out_dir):
        raise SubmissionError("submission has no on-disk layout — call build_submission first")

    manifest = {
        "project_name":   sub.project_name,
        "out_dir":        sub.out_dir,
        "files":          sorted(os.listdir(sub.out_dir)),
        "repo_url":       sub.repo_url,
        "harness_count":  len(sub.harnesses),
        "dry_run":        dry_run,
    }
    if dry_run:
        _record(sub, status="DRY_RUN_OK")
        return {"status": "DRY_RUN_OK", **manifest}

    if not (GH_TOKEN and FORK_OWNER):
        raise SubmissionError(
            "OSS_FUZZ_GH_TOKEN and OSS_FUZZ_FORK_OWNER are required for live submission"
        )

    # 1. Get base SHA from the operator fork.
    base = _gh("GET", f"/repos/{FORK_OWNER}/{UPSTREAM_REPO}/git/ref/heads/{BASE_BRANCH}")
    base_sha = base["object"]["sha"]

    # 2. Create a feature branch on the fork.
    branch = f"rhodawk/oss-fuzz-{sub.project_name}-{int(time.time())}"
    _gh("POST", f"/repos/{FORK_OWNER}/{UPSTREAM_REPO}/git/refs",
        {"ref": f"refs/heads/{branch}", "sha": base_sha})

    # 3. Create blobs + tree under projects/<name>/.
    tree_entries = []
    for fname in sorted(os.listdir(sub.out_dir)):
        with open(os.path.join(sub.out_dir, fname), "rb") as fh:
            content = fh.read()
        blob = _gh("POST", f"/repos/{FORK_OWNER}/{UPSTREAM_REPO}/git/blobs",
                   {"content": content.decode("utf-8"), "encoding": "utf-8"})
        tree_entries.append({
            "path": f"projects/{sub.project_name}/{fname}",
            "mode": "100755" if fname == "build.sh" else "100644",
            "type": "blob",
            "sha":  blob["sha"],
        })

    base_commit = _gh("GET",
        f"/repos/{FORK_OWNER}/{UPSTREAM_REPO}/git/commits/{base_sha}")
    new_tree = _gh("POST", f"/repos/{FORK_OWNER}/{UPSTREAM_REPO}/git/trees",
                   {"base_tree": base_commit["tree"]["sha"], "tree": tree_entries})
    commit = _gh("POST", f"/repos/{FORK_OWNER}/{UPSTREAM_REPO}/git/commits", {
        "message": f"Add {sub.project_name} (Rhodawk auto-submission)",
        "tree":    new_tree["sha"],
        "parents": [base_sha],
    })
    _gh("PATCH", f"/repos/{FORK_OWNER}/{UPSTREAM_REPO}/git/refs/heads/{branch}",
        {"sha": commit["sha"], "force": False})

    # 4. Open the upstream PR.
    pr = _gh("POST", f"/repos/{UPSTREAM_OWNER}/{UPSTREAM_REPO}/pulls", {
        "title": f"Add {sub.project_name}",
        "head":  f"{FORK_OWNER}:{branch}",
        "base":  BASE_BRANCH,
        "body": (
            f"Adding `{sub.project_name}` to OSS-Fuzz.\n\n"
            f"Source repository: {sub.repo_url}\n"
            f"Primary contact: {sub.primary_contact}\n"
            f"Harnesses: {len(sub.harnesses)}\n\n"
            f"_Auto-generated by Rhodawk oss_fuzz_pipeline._"
        ),
        "maintainer_can_modify": True,
    })

    _record(sub, status="PR_OPEN",
            pr_url=pr.get("html_url", ""), pr_number=int(pr.get("number") or 0))
    return {"status": "PR_OPEN", "pr": pr.get("html_url", ""), **manifest}


def discover_status(project_name: str) -> Optional[dict]:
    _init_db()
    with sqlite3.connect(SUBMISSION_DB) as c:
        c.row_factory = sqlite3.Row
        row = c.execute(
            "SELECT * FROM submissions WHERE project_name=?",
            (project_name,),
        ).fetchone()
    return dict(row) if row else None
